### ISSUE TITLE
Table crashes on Singleplayer Japanese/Korean 4ball

### ISSUE THREAD

**Issue by ChildoftheBeast** [FairlySadPanda/vrcbce#79] opened 2021-07-31 21:03 UTC
The table seems to crash when trying to do singleplayer in either Japanese or Korean 4ball. 

It crashes for the person who tried to play. For everyone else, there's a person in slot 1 and there's no game running, seems like it doesn't try to start the game via the network.

You can add yourself to slot 1, add yourself to slot 2, table works as expected, just remains crashed for that person who tried to start the singleplayer game.

**Comment by FairlySadPanda** [comment] 2021-08-01 00:00
Not able to reproduce this on latest local version - keep an eye out on the next release with a newly imported table. If you can, please test this with Udon debugging enabled in client (it needs certain launch arguments - see https://docs.vrchat.com/docs/debugging-udon-projects. Then, if it crashes, post the log output.

**Comment by ChildoftheBeast** [comment] 2021-08-01 01:44
Lines `2401` and `2408` wern't wrapped in a logger check. the crash was caused by the logger not being found when trying to push a string to it.

**Comment by FairlySadPanda** [comment] 2021-08-02 09:49
Fixed in 1.2.2, which is out this week.

**Closed** 2021-10-05 04:16 UTC
